<?php
include '../includes/verify.php';
verify();
include '../includes/connection.php';
include '../includes/utilities.php';

$total_sales = $mysqli->query("SELECT SUM(`total price`) as 'sum' FROM `sold car` WHERE `sold by`='".$_POST["username"]."';");
$all_sales = $total_sales->fetch_array(MYSQLI_NUM);

if(sizeof($all_sales) <= 1) return; //in case the sales person has made no sales, no info cards are displayed

$top_selling_month = $mysqli->query("SELECT SUM(`total price`), MONTH(`datetime`) AS 'years' FROM `sold car` WHERE `sold by`='".$_POST["username"]."' GROUP BY MONTH(`datetime`) ORDER BY SUM(`total price`) DESC LIMIT 1;");
$top_month = $top_selling_month->fetch_array(MYSQLI_NUM);

$months = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
?>

<div style="display: grid; grid-template-columns: 50% 50%; margin-top: 2em;">
    <div class="gross-sales" style="margin: 0 0.5em 0 0; background-color: #41ab7f;">
        <h4>Total Inflow generated by </h4>
        <h1><?php echo $_POST["username"]; ?></h1>
        <h5><?php echo getRupees($all_sales[0]); ?></h5>
    </div>
    <div class="top-company" style="margin: 0 0 0 0.5em; background-color: #3e6089;">
        <h4>Top month of sales for <?php echo $_POST["username"]; ?></h4>
        <h1><?php echo $months[$top_month[1] - 1]; ?></h1>
        <h5><?php echo getRupees($top_month[0]); ?></h5>
    </div>
</div>
